## Numpy Basics

In [1]:
import numpy as np

list_ = [ "1" , "2" , "3" , "4" , "5" ]

array_list = np.array(object = list_)

#### 1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
type(list_)

list

In [3]:
type(array_list)

numpy.ndarray

**AS you can see there is difference between the data types of this two variables ,list_ is of type list and array_list is of type numpy.ndarray**

#### 2. Write a code to print the data type of each and every element of both the variables list_ and array_list.



In [4]:
#code to print each element's data type of a list:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
#code to print each elemnet's data type in an numpy array:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### 3.  Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [6]:
array_list = np.array(object = list_, dtype = int)

In [7]:
#code to print each element's data type of a list:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [8]:
#code to print each elemnet's data type in an numpy array:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


**As you can see,the data type for the array_list's each element has changed to numpy.int32 from numpy.str__.And the list_ variable is unchanged so its elemets are still of type str.**

#### Consider the below code to answer further questions:

In [9]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

#### 4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size




In [10]:
#shape of the numpy array:
print(f"The shape of the array is: {num_array.shape}")

The shape of the array is: (2, 3)


In [11]:
#size of the numpy array:
print(f"The size of the array is: {num_array.size}")

The size of the array is: 6


#### 5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [12]:
num_zeros = np.zeros((3,3))

print(num_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(f"shape:{num_zeros.shape}")

shape:(3, 3)


In [14]:
print(f"size : {num_zeros.size}")

size : 9


#### 6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [15]:
i_mat = np.eye(5)
print(i_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
#other function:
i_mat2 = np.identity(5)
print(i_mat2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
